name: ffi_tool
version: 0.4.0
description: A tool for generating 'dart:ffi' bindings for C and Objective-C libraries.
homepage: https://github.com/dart-interop/ffi_tool

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
